# Generated by Django 5.2.14 on 2026-05-12 20:10

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('normas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoContratual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('icone', models.ImageField(blank=True, null=True, upload_to='objetos/', verbose_name='Ícone')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filhos', to='criterios.objetocontratual', verbose_name='Supercategoria')),
            ],
            options={
                'verbose_name': 'Objeto Contratual',
                'verbose_name_plural': 'Objetos Contratuais',
                'ordering': ['parent__nome', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCriterio',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('codigo', models.CharField(blank=True, db_index=True, help_text='Gerado automaticamente no formato "CRIT-AAAA-NNN" se vazio.', max_length=30, verbose_name='Código')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=300, verbose_name='Slug')),
                ('tipo_contratacao', models.CharField(choices=[('BENS', 'Aquisição de Bens'), ('SERVICOS', 'Contratação de Serviços'), ('SERVICOS_ENGENHARIA', 'Serviços de Engenharia'), ('OBRAS', 'Obras')], default='BENS', max_length=32, verbose_name='Tipo de Contratação')),
                ('fase_processo', models.CharField(choices=[('ETP', 'Estudo Técnico Preliminar'), ('TR_PB', 'Termo de Referência / Projeto Básico'), ('EDITAL', 'Edital de Licitação'), ('EXECUCAO', 'Execução Contratual'), ('FISCALIZACAO', 'Fiscalização do Contrato')], default='TR_PB', max_length=32, verbose_name='Fase do Processo')),
                ('nivel_ambicao', models.CharField(choices=[('BASICO', 'Básico'), ('INTERMEDIARIO', 'Intermediário'), ('AVANCADO', 'Avançado')], default='BASICO', max_length=20, verbose_name='Nível de Ambição')),
                ('texto_providencia', models.TextField(help_text='Trecho pronto para colar em ETP, TR/PB, edital ou contrato.', verbose_name='Texto da Providência')),
                ('determinacoes_principais', models.TextField(help_text='Sumarização das obrigações normativas que dão base ao critério.', verbose_name='Determinações Principais')),
                ('justificativa_tecnica', models.TextField(help_text='Por que o critério faz sentido; problema socioambiental endereçado.', verbose_name='Justificativa Técnica')),
                ('metodo_verificacao', models.TextField(help_text='Como comprovar atendimento (documentos, selos, laudos, fiscalização).', verbose_name='Método de Verificação')),
                ('precaucoes', models.TextField(blank=True, help_text='Riscos, casos de não aplicação, alertas jurisprudenciais.', verbose_name='Precauções e Ressalvas')),
                ('fonte', models.CharField(blank=True, help_text='Ex.: "Guia AGU 2024 — item 27".', max_length=500, verbose_name='Fonte')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADO', 'Publicado'), ('ARQUIVADO', 'Arquivado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('publicado_em', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('objeto_contratual', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='criterios.objetocontratual', verbose_name='Objeto Contratual')),
            ],
            options={
                'verbose_name': 'historical Critério',
                'verbose_name_plural': 'historical Critérios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo', models.CharField(blank=True, help_text='Gerado automaticamente no formato "CRIT-AAAA-NNN" se vazio.', max_length=30, unique=True, verbose_name='Código')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='Slug')),
                ('tipo_contratacao', models.CharField(choices=[('BENS', 'Aquisição de Bens'), ('SERVICOS', 'Contratação de Serviços'), ('SERVICOS_ENGENHARIA', 'Serviços de Engenharia'), ('OBRAS', 'Obras')], default='BENS', max_length=32, verbose_name='Tipo de Contratação')),
                ('fase_processo', models.CharField(choices=[('ETP', 'Estudo Técnico Preliminar'), ('TR_PB', 'Termo de Referência / Projeto Básico'), ('EDITAL', 'Edital de Licitação'), ('EXECUCAO', 'Execução Contratual'), ('FISCALIZACAO', 'Fiscalização do Contrato')], default='TR_PB', max_length=32, verbose_name='Fase do Processo')),
                ('nivel_ambicao', models.CharField(choices=[('BASICO', 'Básico'), ('INTERMEDIARIO', 'Intermediário'), ('AVANCADO', 'Avançado')], default='BASICO', max_length=20, verbose_name='Nível de Ambição')),
                ('texto_providencia', models.TextField(help_text='Trecho pronto para colar em ETP, TR/PB, edital ou contrato.', verbose_name='Texto da Providência')),
                ('determinacoes_principais', models.TextField(help_text='Sumarização das obrigações normativas que dão base ao critério.', verbose_name='Determinações Principais')),
                ('justificativa_tecnica', models.TextField(help_text='Por que o critério faz sentido; problema socioambiental endereçado.', verbose_name='Justificativa Técnica')),
                ('metodo_verificacao', models.TextField(help_text='Como comprovar atendimento (documentos, selos, laudos, fiscalização).', verbose_name='Método de Verificação')),
                ('precaucoes', models.TextField(blank=True, help_text='Riscos, casos de não aplicação, alertas jurisprudenciais.', verbose_name='Precauções e Ressalvas')),
                ('fonte', models.CharField(blank=True, help_text='Ex.: "Guia AGU 2024 — item 27".', max_length=500, verbose_name='Fonte')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADO', 'Publicado'), ('ARQUIVADO', 'Arquivado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('publicado_em', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criterios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('normas', models.ManyToManyField(blank=True, related_name='criterios', to='normas.normalegal', verbose_name='Normas Legais')),
                ('ods', models.ManyToManyField(blank=True, related_name='criterios', to='normas.ods', verbose_name='ODS aplicáveis')),
                ('selos', models.ManyToManyField(blank=True, related_name='criterios', to='normas.selocertificacao', verbose_name='Selos e Certificações')),
                ('tags', models.ManyToManyField(blank=True, related_name='criterios', to='core.tag', verbose_name='Tags')),
                ('objeto_contratual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criterios', to='criterios.objetocontratual', verbose_name='Objeto Contratual')),
            ],
            options={
                'verbose_name': 'Critério',
                'verbose_name_plural': 'Critérios',
                'ordering': ['-updated'],
            },
        ),
        migrations.AddIndex(
            model_name='objetocontratual',
            index=models.Index(fields=['ativo', 'ordem'], name='criterios_o_ativo_1fbe96_idx'),
        ),
        migrations.AddIndex(
            model_name='criterio',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='pescp_crit_search_gin'),
        ),
        migrations.AddIndex(
            model_name='criterio',
            index=models.Index(fields=['status', 'objeto_contratual'], name='criterios_c_status_49fca2_idx'),
        ),
        migrations.AddIndex(
            model_name='criterio',
            index=models.Index(fields=['fase_processo', 'nivel_ambicao'], name='criterios_c_fase_pr_a61120_idx'),
        ),
    ]
