# Generated by Django 5.2.14 on 2026-05-12 20:10

import apps.conteudo.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criterios', '0001_initial'),
        ('normas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('conteudo', models.TextField(help_text='HTML sanitizado ou markdown. É renderizado com |safe — não exponha campo a usuários externos.', verbose_name='Conteúdo (HTML/markdown)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem (menu)')),
                ('publicada', models.BooleanField(default=True, verbose_name='Publicada?')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Meta description (SEO)')),
            ],
            options={
                'verbose_name': 'Página institucional',
                'verbose_name_plural': 'Páginas institucionais',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to=apps.conteudo.models._document_upload_path, verbose_name='Arquivo')),
                ('tipo', models.CharField(choices=[('MODELO_CLAUSULA', 'Modelo de cláusula'), ('PLANILHA', 'Planilha'), ('GUIA', 'Guia técnico'), ('RELATORIO_IMPACTO', 'Relatório de impacto'), ('OUTRO', 'Outro')], default='GUIA', max_length=32, verbose_name='Tipo')),
                ('tamanho_bytes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('extensao', models.CharField(blank=True, max_length=10, verbose_name='Extensão')),
                ('objeto_contratual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_apoio', to='criterios.objetocontratual', verbose_name='Objeto Contratual relacionado')),
            ],
            options={
                'verbose_name': 'Documento de Apoio',
                'verbose_name_plural': 'Documentos de Apoio',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPaginaInstitucional',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='Slug')),
                ('conteudo', models.TextField(help_text='HTML sanitizado ou markdown. É renderizado com |safe — não exponha campo a usuários externos.', verbose_name='Conteúdo (HTML/markdown)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem (menu)')),
                ('publicada', models.BooleanField(default=True, verbose_name='Publicada?')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Meta description (SEO)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Página institucional',
                'verbose_name_plural': 'historical Páginas institucionais',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TermoGlossario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('termo', models.CharField(max_length=200, unique=True, verbose_name='Termo')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('definicao', models.TextField(verbose_name='Definição')),
                ('sigla', models.CharField(blank=True, max_length=20, verbose_name='Sigla')),
                ('normas_relacionadas', models.ManyToManyField(blank=True, related_name='termos_glossario', to='normas.normalegal', verbose_name='Normas relacionadas')),
            ],
            options={
                'verbose_name': 'Termo do Glossário',
                'verbose_name_plural': 'Glossário',
                'ordering': ['termo'],
            },
        ),
    ]
