# Generated by Django 5.2.14 on 2026-05-12 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criterios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotoLicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo', models.CharField(blank=True, help_text='Gerado automaticamente como "PIL-AAAA-NNN" se vazio.', max_length=30, unique=True, verbose_name='Código')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título descritivo')),
                ('unidade_compradora', models.CharField(help_text='Secretaria, autarquia, fundação, etc.', max_length=300, verbose_name='Unidade Compradora')),
                ('tipo_contratacao', models.CharField(choices=[('BENS', 'Aquisição de Bens'), ('SERVICOS', 'Contratação de Serviços'), ('SERVICOS_ENGENHARIA', 'Serviços de Engenharia'), ('OBRAS', 'Obras')], default='BENS', max_length=32, verbose_name='Tipo de Contratação')),
                ('estagio_atual', models.CharField(choices=[('PLANEJAMENTO', 'Planejamento'), ('EDITAL_PUBLICADO', 'Edital publicado'), ('EM_LICITACAO', 'Em licitação'), ('HOMOLOGADO', 'Homologado'), ('EM_EXECUCAO', 'Em execução'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PLANEJAMENTO', max_length=32, verbose_name='Estágio atual')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor estimado (R$)')),
                ('valor_homologado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor homologado (R$)')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Início')),
                ('data_homologacao', models.DateField(blank=True, null=True, verbose_name='Homologação')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Conclusão')),
                ('numero_processo_sei', models.CharField(blank=True, max_length=50, verbose_name='Processo SEI')),
                ('numero_edital', models.CharField(blank=True, max_length=50, verbose_name='Número do Edital')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('publicar_pagina', models.BooleanField(default=False, help_text='Na v1.0 permanece sempre False — pilotos só visíveis no Admin.', verbose_name='Publicar página pública (v2.0)')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilotos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('criterios_aplicados', models.ManyToManyField(blank=True, related_name='pilotos', to='criterios.criterio', verbose_name='Critérios aplicados')),
                ('objeto_contratual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilotos', to='criterios.objetocontratual', verbose_name='Objeto Contratual')),
            ],
            options={
                'verbose_name': 'Piloto de Licitação',
                'verbose_name_plural': 'Pilotos de Licitação',
                'ordering': ['-data_inicio', '-created'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoImpacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('economia_lcc_estimada', models.DecimalField(blank=True, decimal_places=2, help_text='Life Cycle Cost — economia do ciclo de vida em relação à contratação tradicional.', max_digits=14, null=True, verbose_name='Economia LCC estimada (R$)')),
                ('reducao_co2_estimada_ton', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Redução de CO₂ estimada (toneladas)')),
                ('impactos_sociais', models.TextField(blank=True, verbose_name='Impactos sociais')),
                ('impactos_ambientais', models.TextField(blank=True, verbose_name='Impactos ambientais')),
                ('licoes_aprendidas', models.TextField(blank=True, verbose_name='Lições aprendidas')),
                ('recomendacoes_para_proximas_contratacoes', models.TextField(blank=True, verbose_name='Recomendações para próximas contratações')),
                ('data_avaliacao', models.DateField(blank=True, null=True, verbose_name='Data da avaliação')),
                ('piloto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='pilotos.pilotolicitacao', verbose_name='Piloto')),
            ],
            options={
                'verbose_name': 'Avaliação de Impacto',
                'verbose_name_plural': 'Avaliações de Impacto',
            },
        ),
        migrations.AddIndex(
            model_name='pilotolicitacao',
            index=models.Index(fields=['estagio_atual'], name='pilotos_pil_estagio_99b6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='pilotolicitacao',
            index=models.Index(fields=['tipo_contratacao'], name='pilotos_pil_tipo_co_b10b2d_idx'),
        ),
    ]
