# Generated by Django 5.2.14 on 2026-05-12 20:10

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero', models.PositiveSmallIntegerField(unique=True, verbose_name='Número (1 a 17)')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('descricao_curta', models.CharField(blank=True, max_length=300, verbose_name='Descrição curta')),
                ('descricao_longa', models.TextField(blank=True, verbose_name='Descrição longa')),
                ('cor_hex', models.CharField(default='#000000', help_text='Cor oficial definida pela ONU para o ODS (ex.: #E5243B para ODS 1).', max_length=7, verbose_name='Cor oficial (#HEX)')),
                ('icone', models.ImageField(blank=True, help_text='Ícone oficial da ONU. Coloque o arquivo em media/ods/.', null=True, upload_to='ods/', verbose_name='Ícone oficial')),
                ('metas', models.JSONField(blank=True, default=list, help_text='Lista de strings com as metas (ex.: ["1.1 ...", "1.2 ..."]).', verbose_name='Metas oficiais')),
            ],
            options={
                'verbose_name': 'ODS',
                'verbose_name_plural': 'ODS (Objetivos de Desenvolvimento Sustentável)',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='SeloCertificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('link_oficial', models.URLField(blank=True, verbose_name='Link oficial')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='selos/', verbose_name='Logo')),
                ('tipo', models.CharField(choices=[('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional'), ('SETORIAL', 'Setorial')], default='NACIONAL', max_length=20, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Selo / Certificação',
                'verbose_name_plural': 'Selos e Certificações',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='NormaLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('titulo_curto', models.CharField(help_text='Ex.: "Lei 14.133/2021"', max_length=200, verbose_name='Título curto')),
                ('titulo_completo', models.CharField(help_text='Ex.: "Lei nº 14.133, de 1º de abril de 2021..."', max_length=500, verbose_name='Título completo')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('tipo', models.CharField(choices=[('CONSTITUCIONAL', 'Constitucional'), ('LEI_FEDERAL', 'Lei Federal'), ('LEI_ESTADUAL', 'Lei Estadual'), ('LEI_MUNICIPAL', 'Lei Municipal'), ('DECRETO_FEDERAL', 'Decreto Federal'), ('DECRETO_ESTADUAL', 'Decreto Estadual'), ('DECRETO_MUNICIPAL', 'Decreto Municipal'), ('INSTRUCAO_NORMATIVA', 'Instrução Normativa'), ('RESOLUCAO', 'Resolução'), ('PORTARIA', 'Portaria'), ('NBR_ABNT', 'NBR/ABNT'), ('INTERNACIONAL', 'Acordo/Resolução Internacional'), ('OUTRO', 'Outro')], default='LEI_FEDERAL', max_length=32, verbose_name='Tipo')),
                ('esfera', models.CharField(choices=[('FEDERAL', 'Federal'), ('ESTADUAL', 'Estadual'), ('MUNICIPAL', 'Municipal'), ('INTERNACIONAL', 'Internacional')], default='FEDERAL', max_length=16, verbose_name='Esfera')),
                ('numero', models.CharField(blank=True, max_length=50, verbose_name='Número')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data de publicação')),
                ('data_vigencia', models.DateField(blank=True, null=True, verbose_name='Data de início de vigência')),
                ('revogada', models.BooleanField(default=False, verbose_name='Revogada?')),
                ('link_oficial', models.URLField(blank=True, help_text='URL no DOU, planalto.gov.br, doe.sp.gov.br, etc.', verbose_name='Link oficial')),
                ('ementa', models.TextField(blank=True, verbose_name='Ementa')),
                ('revogada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normas_revogadas', to='normas.normalegal', verbose_name='Revogada por')),
            ],
            options={
                'verbose_name': 'Norma Legal',
                'verbose_name_plural': 'Normas Legais',
                'ordering': ['esfera', 'titulo_curto'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalNormaLegal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('titulo_curto', models.CharField(help_text='Ex.: "Lei 14.133/2021"', max_length=200, verbose_name='Título curto')),
                ('titulo_completo', models.CharField(help_text='Ex.: "Lei nº 14.133, de 1º de abril de 2021..."', max_length=500, verbose_name='Título completo')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='Slug')),
                ('tipo', models.CharField(choices=[('CONSTITUCIONAL', 'Constitucional'), ('LEI_FEDERAL', 'Lei Federal'), ('LEI_ESTADUAL', 'Lei Estadual'), ('LEI_MUNICIPAL', 'Lei Municipal'), ('DECRETO_FEDERAL', 'Decreto Federal'), ('DECRETO_ESTADUAL', 'Decreto Estadual'), ('DECRETO_MUNICIPAL', 'Decreto Municipal'), ('INSTRUCAO_NORMATIVA', 'Instrução Normativa'), ('RESOLUCAO', 'Resolução'), ('PORTARIA', 'Portaria'), ('NBR_ABNT', 'NBR/ABNT'), ('INTERNACIONAL', 'Acordo/Resolução Internacional'), ('OUTRO', 'Outro')], default='LEI_FEDERAL', max_length=32, verbose_name='Tipo')),
                ('esfera', models.CharField(choices=[('FEDERAL', 'Federal'), ('ESTADUAL', 'Estadual'), ('MUNICIPAL', 'Municipal'), ('INTERNACIONAL', 'Internacional')], default='FEDERAL', max_length=16, verbose_name='Esfera')),
                ('numero', models.CharField(blank=True, max_length=50, verbose_name='Número')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data de publicação')),
                ('data_vigencia', models.DateField(blank=True, null=True, verbose_name='Data de início de vigência')),
                ('revogada', models.BooleanField(default=False, verbose_name='Revogada?')),
                ('link_oficial', models.URLField(blank=True, help_text='URL no DOU, planalto.gov.br, doe.sp.gov.br, etc.', verbose_name='Link oficial')),
                ('ementa', models.TextField(blank=True, verbose_name='Ementa')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revogada_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='normas.normalegal', verbose_name='Revogada por')),
            ],
            options={
                'verbose_name': 'historical Norma Legal',
                'verbose_name_plural': 'historical Normas Legais',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='normalegal',
            index=models.Index(fields=['esfera', 'tipo'], name='normas_norm_esfera_164c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='normalegal',
            index=models.Index(fields=['revogada'], name='normas_norm_revogad_c155d2_idx'),
        ),
    ]
